### ISSUE TITLE
Belt length of pan axis

### ISSUE THREAD

**Issue by Merimaa** [Adamslab/OpenSlider#13]
Hi,

first of all thanks for the design.

I have a problem with the belt length of the pan axis. The 250mm belt is round about 6mm to long. For the tilt axis the 250mm belt fits perfect. Am I doing something wrong?
![20190822_111108small](https://user-images.githubusercontent.com/52958784/63503697-42889600-c4d0-11e9-9eff-6c6becdbc3a1.jpg)

Thanks in advance.

Merimaa

**Comment by Adamslab** [comment]
You're right, I made the wrong measurements with my earlier versions. I'm working on releasing a newer version of the X and Y axis that will work for a 248mm to 258mm belt loop length.
