### ISSUE TITLE
Request: Source for models

### ISSUE THREAD

**Issue by dushyantahuja** [Adamslab/OpenSlider#16]
Hi - first of all, thanks a lot for this. I am trying to use equipment that I have lying around, and hence need to modify some of the models. e.g. for the X axis, I would rather use 2020, instead of 2040 - as I have many lying with me. Same for the closed loop belts - I'd like to modify the design to use 200mm belts instead.

Can you please share the editable models.

**Comment by Adamslab** [comment]
Hi,

Sorry for the delay in responding to this issue. I'll upload the files in a few other formats so they can be edited. What format do you need?

**Comment by dushyantahuja** [comment]
No problems - I edited the STLs using TinkerCAD :-)
However, step files / fusion3D files would be nice.
------------------
Dushyant Ahuja

**Comment by Adamslab** [comment]
Glad to hear you got it working. If you'd like to add your modified version to the Github project that would be great. I added .STEP files for the X-Axis to the github.

**Comment by dushyantahuja** [comment]
Thanks.
Modified models are in my fork:
https://github.com/dushyantahuja/OpenSlider

Can't submit a pull request - as I've deleted off all the Marlin stuff, and don't know enough about github to be able to submit a partial pull request.

**Comment by Adamslab** [comment]
I can add your files and provide credit back to you.

**Comment by dushyantahuja** [comment]
Be my guest.
